/*
 * myerror.h
 *
 *  Created on: Jul 2, 2023
 *      Author: Admin
 */

#ifndef INC_MYERROR_H_
#define INC_MYERROR_H_

#define DC_DC_Circuit_Excessive_Leakage     			0xF001 // Fault F001: DC-DC Circuit Excessive Leakage - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define PFC_Circuit_Excessive_Leakage          			0xF002 // Fault F002: PFC Circuit Excessive Leakage - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define PFC_Circuit_Boost_Failure             			0xF003 // Fault F003: PFC Circuit Boost Failure - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Battery_Current_Sense_Circuit_Failure   		0xF004 // Fault F004: Battery Current Sense Circuit Failure - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define DC_Relay_Circuit_Rationality           			0xF005 // Fault F005: DC Relay Circuit - Rationality - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Battery_Current_Sense_Circuit_Rationality 		0xF006 // Fault F006: Battery Current Sense Circuit Rationality - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define DC_DC_Circuit_Failure                  			0xF007 // Fault F007: DC-DC Circuit Failure - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Error_Code_F008                        			0xF008 // Fault F008: Not Used
#define Internal_Software_Exception            			0xF009 // Fault F009: Internal Software Exception - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Fault_on_Connected_Charger              		0xF010 // Fault F010: Fault on Connected Charger - Stackable and VCIM systems: Check connected chargers individually for faults.
#define Error_Code_F011                        			0xF011 // Fault F011:
#define Error_Code_F012                        			0xF012 // Fault F012:
#define Error_Code_F013                        			0xF013 // Fault F013:
#define Error_Code_F014                        			0xF014 // Fault F014:
#define Error_Code_F015                        			0xF015 // Fault F015:
#define Internal_Aux_Relay_Circuit_Fault        		0xF016 // Fault F016: Internal Aux Relay Circuit Fault - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Control_Pilot_Voltage_Range_Issue       		0xF017 // Fault F017: Control Pilot Voltage Range Issue - Check EVSE for proper operation. Check control pilot wire for damage. Possible internal hardware fault. If persists, replace the unit.
#define Aux_Output_Fuse_Circuit_Failure         		0xF018 // Fault F018: Aux Output Fuse Circuit Failure - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Aux_Output_Voltage_Too_High             		0xF019 // Fault F019: Aux Output Voltage too High - Check AUX DC connected to correct voltage battery (12V or 24V). Possible internal hardware fault. If persists, replace the unit.
#define Internal_Aux_DCDC_Short_Circuit         		0xF020 // Fault F020: Internal Aux DCDC Short Circuit - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Internal_Temperature_Sensor_Fault       		0xF021 // Fault F021: Internal Temperature Sensor Fault - Internal charger fault. Remove AC and battery for minimum 30 MINUTES and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Internal_Aux_DCDC_Circuit_Failure       		0xF022 // Fault F022: Internal Aux DCDC Circuit Failure - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define PFC_Circuit_Performance_Issue_Detected  		0xF023 // Fault F023: PFC Circuit Performance Issue Detected - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Internal_Aux_DCDC_Failed_to_Turn_On     		0xF024 // Fault F024: Internal Aux DCDC Failed to Turn On - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.
#define Internal_Hardware_Clock_Fault           		0xF025 // Fault F025: Internal Hardware Clock Fault - Internal charger fault. Remove AC and battery for minimum 30 seconds and retry charger. If it fails again, do not continue to use the charger - replace the unit.



#define High_Battery_Voltage_Error                             				0xE001 // Alarm E001: High Battery Voltage Error - Battery Voltage is too high to start charge. Check the battery voltage and cable connections. Check battery size and condition. This error will automatically clear once the condition has been corrected.
#define Low_Battery_Voltage_Error                              				0xE002 // Alarm E002: Low Battery Voltage Error - Battery Voltage is too low to start charge. Check the battery voltage and cable connections. Check battery size and condition. This error will automatically clear once the condition has been corrected.
#define Charge_Timeout                                         				0xE003 // Alarm E003: Charge Timeout - Charge Timeout caused by battery pack not reaching required voltage within safe time limit. Possible causes: Charger output reduced due to high temperatures or low AC voltage. Poor battery health. Very deeply discharged battery. Poorly connected battery. Extra loads. Battery too large for algorithm selected. Possible solutions: Improve cooling air flow. Check for low AC voltage. Replace battery pack. Check DC connections. This error will automatically clear once the charger is reset by cycling DC.
#define Battery_Defective                                      				0xE004 // Alarm E004: Battery Defective - Battery could not be trickle charged up to the minimum voltage. Check for shorted or damaged cells. Check battery pack voltage matches charger voltage. Replace battery pack. Check DC connections. This error will automatically clear once the charger is reset by cycling DC.
#define Algorithm_Specific_Alarm                               				0xE005 // Alarm E005: Algorithm Specific Alarm - Contact Support for details if this alarm occurs.
#define Battery_Temperature_Sensor_Short_Circuit              			 	0xE006 // Alarm E006: Battery Temperature Sensor Short Circuit - Check temperature sensor wiring for short to ground then restart the charge.
#define Battery_Temperature_Too_High                      			     	0xE007 // Alarm E007: Battery Temperature Too High - Battery Temperature is above 50°C (122°F). Allow battery to cool before charging. Check for ventilation problems. Check for obstructions blocking air flow around battery. Check that charger is not located in hot area.
#define Battery_Temperature_Too_Low                      			      	0xE008 // Alarm E008: Battery Temperature Too Low - Battery Temperature is below 0°C (32°F). Allow battery to warm up before charging. Check for ventilation problems. Check for obstructions blocking air flow around battery. Check that charger is not located in cold area.
#define Charger_Overtemperature_Error                  			        	0xE009 // Alarm E009: Charger Overtemperature Error - Charger temperature exceeds normal operating range. Check for ventilation problems. Check for obstructions blocking air flow around charger. Clean dirt, debris, or foreign objects from charger.
#define DC_Overvoltage_Error                             			      	0xE010 // Alarm E010: DC Overvoltage Error - Charger DC output voltage exceeds the maximum allowable limit. Check the DC voltage at the charger terminals. Check the charger rating compared to the battery voltage. Check the charger setting compared to the battery voltage. Check for other voltage sources on the DC line.
#define DC_Undervoltage_Error                          			        	0xE011 // Alarm E011: DC Undervoltage Error - Charger DC output voltage is below the minimum allowable limit. Check the DC voltage at the charger terminals. Check the charger rating compared to the battery voltage. Check the charger setting compared to the battery voltage. Check for poor connections or bad wiring on the DC line.
#define AC_Overvoltage_Error                            			       	0xE012 // Alarm E012: AC Overvoltage Error - AC input voltage is higher than the maximum allowable limit. Check the AC voltage at the charger terminals. Check the AC supply wiring and connections. Check for other voltage sources on the AC line.
#define AC_Undervoltage_Error                          			        	0xE013 // Alarm E013: AC Undervoltage Error - AC input voltage is lower than the minimum allowable limit. Check the AC voltage at the charger terminals. Check the AC supply wiring and connections.
#define AC_Frequency_Error                            			         	0xE014 // Alarm E014: AC Frequency Error - AC input frequency is outside the allowable range. Check the AC frequency at the charger terminals. Check the AC supply wiring and connections.
#define Battery_Overcurrent_Error                             			 	0xE015 // Alarm E015: Battery Overcurrent Error - Charge current exceeds the maximum allowable limit. Check battery size and condition. Check for loose or corroded cable connections. Check for shorted cells or cables. Check for poor contact in charging socket. Check the charger rating compared to the battery voltage.
#define External_Interference_Error                            				0xE016 // Alarm E016: External Interference Error - The charger detects high levels of external interference affecting its operation. Check for nearby sources of electromagnetic interference. Relocate charger if necessary.
#define DC_Sensor_Fault                                        				0xE017 // Alarm E017: DC Sensor Fault - The charger's DC sensor is reporting an error. Contact Support for further assistance.
#define AC_Sensor_Fault                                        				0xE018 // Alarm E018: AC Sensor Fault - The charger's AC sensor is reporting an error. Contact Support for further assistance.
#define Charger_Programming_Failure_Incorrect_Software         				0xE019 // Alarm E019: Charger Programming Failure - Incorrect Software - The charger hardware does not support the software version being programmed. Existing software is left running. Contact Support.
#define No_Active_Algorithm_Selected                           				0xE020 // Alarm E020: No Active Algorithm Selected - Select a charge profile using the button or reflash the charger.
#define High_Battery_Voltage_Error_While_Charging             			 	0xE021 // Alarm E021: High Battery Voltage Error While Charging - Battery Voltage is too high as detected by the algorithm. Check the battery voltage and cable connections. This error will automatically clear once the condition has been corrected.
#define Low_Battery_Voltage_Error_While_Charging              			 	0xE022 // Alarm E022: Low Battery Voltage Error While Charging - Battery Voltage is too low as detected by the algorithm. Check the battery voltage and cable connections. This error will automatically clear once the condition has been corrected.
#define AC_Voltage_High                                      			  	0xE023 // Alarm E023: AC Voltage High - AC voltage is too high. Connect charger to an AC source that provides stable AC between 85 - 270 VAC / 45-65 Hz. This error will automatically clear once the condition has been corrected.
#define Charger_Initialization_Failure                         				0xE024 // Alarm E024: Charger Initialization Failure - The charger has failed to turn on properly. Disconnect AC and battery for 30 seconds before retrying. If Error persists, contact Support.
#define AC_Voltage_Unstable_and_Low                          			  	0xE025 // Alarm E025: AC Voltage Unstable and Low - AC source is unstable. Could be caused by undersized generator and/or severely undersized/long AC cables. Connect charger to an AC source that is stable and between 85 - 270 VAC / 45-65 Hz. This error will automatically clear once the condition has been corrected.
#define USB_Script_Failure                                   			  	0xE026 // Alarm E026: USB Script Failure - Retry by removing and re-inserting the USB drive. Ensure correct files are being used. Ensure the USB Flash Drive is properly formatted (FAT recommended) and retry. Try a different USB drive. If error persists, contact Support.
#define USB_Over_Current_Fault                               			  	0xE027 // Alarm E027: USB Over Current Fault - USB hardware overcurrent protection has been tripped. Remove and reinsert USB device. If the condition persists then try a different, brand-name USB device.
#define Incompatible_Algorithm                                			 	0xE028 // Alarm E028: Incompatible Algorithm - The selected charging profile is incompatible with the charger software. Update charger software or select a different charging profile.
#define CAN_Bus_Physical_Layer_Error                          			 	0xE029 // Alarm E029: CAN Bus Physical Layer Error - CAN bus network error. Check the physical CAN connector, wiring, and other CAN modules for correct functioning. Check termination is around 60 ohms.
#define Battery_Reporting_Error                               				0xE030 // Alarm E030: Battery Reporting Error - Charger has received an error from the battery module or it is in a pre-operational state.
#define Internal_Charger_Power_Supply_Error                    				0xE031 // Alarm E031: Internal Charger Power Supply Error - Internal supply rail error detected. Remove AC and battery for minimum 30 seconds and retry charger. If the problem persists contact Support.
#define Missing_CAN_Messages                                   				0xE032 // Alarm E032: Missing CAN Messages - CAN heartbeats or PDOs were received and then timed out. Check other CAN devices for function.
#define Configuration_Error_Target_Voltage_Too_High            				0xE033 // Alarm E033: Configuration Error - Target Voltage Too High - The charger configuration is asking for more voltage than the charger can deliver. Charger reflash is required to correct this issue.
#define Configuration_Error_Battery_Capacity_Not_Supported     				0xE034 // Alarm E034: Configuration Error - Battery Capacity Not Supported - Charger is configured with capacity scaling but algorithm selected does not support this feature. Select a scalable algorithm or reflash the charger.
#define Configuration_Error_Target_Voltage_Too_Low             				0xE035 // Alarm E035: Configuration Error - Target Voltage Too Low - The charger configuration is asking for voltage below 20% of the charger nominal. Charger reflash is required to correct this issue.
#define Battery_Temperature_Open_Circuit                       				0xE036 // Alarm E036: Battery Temperature Open Circuit - Check if sensor is connected correctly. Install a temperature sensor. Change to an algorithm that does not require a temperature sensor.
#define Charger_Programming_Failure_CAN                        				0xE037 // Alarm E037: Charger Programming Failure - CAN - Re-try CANOpen download or re-program using the USB
#define Cooling_Fan_Error                                      				0xE038 // Alarm E038: Cooling Fan Error - Inspect fan to make sure the power wires are connected and the fan blades are not obstructed by debris.
#define Button_Stuck_Down                                      				0xE039 // Alarm E039: Button Stuck Down - Inspect for objects on or near the button or damage to the button. If alarm persists, replace charger.
#define Cooling_Fan_Voltage_Too_Low                            				0xE040 // Alarm E040: Cooling Fan Voltage Too Low - Ensure that the fan is not stuck or drawing excess current, and that the correct fan part is installed.
#define Software_Error_General                                 				0xE041 // Alarm E041: Software Error - General - Software internal configuration error, ensure configuration settings are correct and reflash charger.
#define Configuration_Error_CAN                                				0xE042 // Alarm E042: Configuration Error - CAN - Software internal configuration error, ensure configuration settings are correct and reflash charger.
#define CANopen_PDO_CRC_Mismatch                               				0xE043 // Alarm E043: CANopen PDO CRC Mismatch - Power cycle all CAN nodes and charger. Error will clear once sequence counter updates. Reflash charger if this persists. CAN only - not shown on display.
#define CANopen_PDO_Sequence_Count_Not_Changing              			  	0xE044 // Alarm E044: CANopen PDO Sequence Count Not Changing - Power cycle all CAN nodes and charger. Error will clear once sequence counter updates. Reflash charger if this persists. CAN only - not shown on display.
#define Charger_Output_Open_Circuit                     			       	0xE045 // Alarm E045: Charger Output Open Circuit - Charger did not see enough battery voltage. Connect the battery in order to start charging. This alarm is only displayed if configured.
#define CAN_Invalid_PDO_Length                        			         	0xE046 // Alarm E046: CAN - Invalid PDO Length - Power cycle all CAN nodes and charger. Error will clear once sequence counter updates. Reflash charger if this persists.
#define Reserved_Alarm_E047                        			            	0xE047 // Alarm E047: Reserved - For internal use
#define Stackable_Charging_Multiple_Masters              			      	0xE048 // Alarm E048: Stackable Charging - Multiple Masters - Check the wiring harness to ensure only one charger has pins populated to be parallel charging master.
#define Stackable_Charging_More_Secondary_Chargers_Than_Expected 			0xE049 // Alarm E049: Stackable Charging - More Secondary Chargers Than Expected - Make sure the right number of chargers are on the bus for this fixed configuration. Reset chargers to check if this alarm persists.
#define Stackable_Charging_No_Master                           				0xE051 // Alarm E051: Stackable Charging - No Master - Master device may be disconnected or powered down. Check wiring harness. Check configuration of devices. Reflash Master charger.
#define Stackable_Charging_Incompatible_Secondary_Chargers     				0xE063 // Alarm E063: Stackable Charging - Incompatible Secondary Charger(s) - Query the master to identify which secondary has the bad configuration or interface version.
#define Stackable_Charging_Single_Charger_Detected_Stackable_Messages 		0xE050 // Alarm E050: Stackable Charging - Single Charger Detected Stackable Messages - Check the configuration of all chargers that are sharing this bus.
#define Stackable_Charging_Fewer_Secondary_Chargers_Than_Expected 			0xE052 // Alarm E052: Stackable Charging - Fewer Secondary Chargers Than Expected - Secondary chargers may be disconnected or powered down. Check the wiring and power to the secondary chargers. The alarm will automatically clear when the missing chargers come back online.
#define Stackable_Charging_Secondary_Charger_Reverse_Polarity     			0xE054 // Alarm E054: Stackable Charging - Secondary Charger Reverse Polarity - Check the DC connections of all chargers and the battery.
#define Stackable_Charging_Secondary_Charger_DC_Voltage_Mismatch 			0xE055 // Alarm E055: Stackable Charging - Secondary Charger DC Voltage Mismatch - Either they are disconnected from each other or there is an excessive series resistance which may result in cable overheating. Check DC output wiring of the entire stack. The problem might be due to loose or corroded connections in the cabling.
#define Stackable_Charging_Communications_Lost_With_Secondary_Charger(s) 	0xE053 // Alarm E053: Stackable Charging - Communications Lost With Secondary Charger(s) - Check wiring harness and power to secondary chargers. Check to see if Secondary Chargers are issuing faults of their own.
#define Reserved_Alarm_E057                                    				0xE057 // Alarm E057: Reserved - Customer specific implementation
#define Reserved_Alarm_E058                                    				0xE058 // Alarm E058: Reserved - Customer specific implementation
#define J1939_Address_Conflict                                				0xE059 // Alarm E059: J1939 Address Conflict - Investigate and disconnect non-compliant device from the bus. Alternatively change the charger's configuration to exclude the conflicted address from its allowed range of addresses.
#define CAN_Communications_Never_Received                       			0xE060 // Alarm E060: CAN Communications Never Received - Charger is waiting for this message to start. Check CAN cabling. Ensure nodes configured to send expected messages.
#define CAN_Battery_Current_Report_Mismatch                     			0xE061 // Alarm E061: CAN Battery Current Report Mismatch - The charger compares the Battery written current with its output current. Check that the right current is being sent to the charger. Check if the output cable has a parallel branch.
#define CAN_Battery_Voltage_Report_Mismatch                     			0xE062 // Alarm E062: CAN Battery Voltage Report Mismatch - The charger compares the Battery written voltage with its output voltage. Check that the correct voltage is being sent to the charger. Check that the output cable resistance matches the charger setting. Check for other sources of voltage drop.
#define Stackable_Charging_Secondary_Charger_Fault_or_Alarm    				0xE056 // Alarm E056: Stackable Charging - Secondary Charger Fault or Alarm - Check for alarms and faults reported by the secondary chargers.
#define J1939_Address_Charger_Failed_to_Claim                  				0xE064 // Alarm E064: J1939 Address - Charger
#define J1939_Address_Other_Device_Failed_to_Claim							0xE065 // Alarm E065: Read SPN 611 from the charger(s) that has raised this alarm. This will contain the 64-bit J1939 "Name" of the device that could not claim its address (see J1939-81 Network Management, Feb 2016, Section 4.2.1 ). If this device is another Delta-Q charger (manufacturer code 800, function Id 141) and this is a stackable charging system then possible causes include: i) Incorrectly configured chargers ii ) Address conflicts exist between the charger and other devices on the bus iii ) Master/Secondary wiring fault. The alarm will be cleared on charger reset - but may immediately trigger if the address conflict persists.
#define Battery_Voltage_Higher_Than_Configured_Maximum   					0xE066 // Alarm E066: Battery Voltage Higher Than Configured Maximum - Check if the charger is connected to the right battery, or the maximum voltage configured is too low.
#define CAN_Physical_Layer_Error_Before_Messages_Received 					0xE067 // Alarm E067: CAN Physical Layer Error - Before Messages Received - CANbus network error. Check the physical CAN connector, electrical bus conditions and other CAN modules for correct functioning. For example, check termination resistance is approximately 60ohms.
#define Missing_CAN_Messages_While_Not_Charging         					0xE068 // Alarm E068: Missing CAN Messages While Not Charging - Monitored messages (Heartbeat, PGN, PDO) lost while charger output off. Check the networked CANbus device(s) for correct function and messages.
#define Accessory_Power_Output_Overcurrent              					0xE069 // Alarm E069: Accessory Power Output Overcurrent - Accessory Power Output (APO) has too much load, please check circuits attached to Accessory Power Output (APO) for shorts or other circuit faults.
#define Charger_Error_Monitor_Triggered                  					0xE087 // Alarm E087: Charger Error Monitor Triggered - Internal error has been flagged due to not generating the regular "watchdog" message. Check for low AC voltage or other abnormal conditions. If this error reappears, replace the charger.
#define Charger_Error_Monitor_Not_Started                					0xE088 // Alarm E088: Charger Error Monitor Not Started - Internal error has been flagged due to loss of communications internally within the charger. Check for abnormal conditions. If this error reappears, replace the charger.
#define Aux_DC_Output_Error                              					0xE089 // Alarm E089: Aux DC Output Error - Lost a condition to operate the Aux DC Output. Check: Aux battery voltage between 9.7-14.5V, Traction battery voltage in range (see Design Guide). Could also be internal hardware failure causing Aux DC Output to be off when commanded on by software or key switch.
#define EVSE_Failed_To_Provide_AC                        					0xE090 // Alarm E090: EVSE Failed To Provide AC - Charger is communicating with EVSE but it is not providing AC. Check EVSE is connected to AC power. Check cables and connections. Check EVSE hardware or try another EVSE.
#define EVSE_Failed_To_Turn_Off_AC                       					0xE091 // Alarm E091: EVSE Failed To Turn Off AC - Charger is communicating with EVSE but it is not turning off AC. Check EVSE contactor for welding. Check cables and connections. If persists, try another EVSE.
#define Charger_Reflash_Error                            					0xE092 // Alarm E092: Charger Reflash Error - Check the configuration file is appropriate for this charger model. Check use of the correct version of programming tool or protocol.
#define Aux_DC_Output_Short_Circuit                     					0xE093 // Alarm E093: Aux DC Output Short Circuit - Check for wiring errors. Check for faulty or shorted battery cells. Check for too much load on Aux Output.
#define AC_Input_Voltage_High_Spikes                     					0xE094 // Alarm E094: AC Input Voltage High Spikes - Monitor for stable AC voltage. Frequent spikes above 280VAC may damage the charger input.
#define Safe_Disconnect_Alarm                            					0xE095 // Alarm E095: Safe Disconnect Alarm - Safe disconnect pin not connected but the primary contact pin connected. Ensure correct style of connector is used and the pins are installed correctly.
#define Charger_Operating_Voltage_Too_Low                 					0xE096 // Alarm E096: Charger Operating Voltage Too Low - Raise charger output voltage above 21.0VDC to reduce thermal stress to internal components.




#endif /* INC_MYERROR_H_ */
